// Decorator & Florist Categories
export const DECORATOR_FLORIST_CATEGORIES = [
  // FLORIST SERVICES
  'Wedding Florist',
  'Event Florist',
  'Corporate Florist',
  'Funeral Florist',
  'Bouquet Designer',
  'Floral Arrangements',
  'Fresh Flowers',
  'Dried Flowers',
  'Artificial Flowers',
  'Seasonal Flowers',
  'Exotic Flowers',
  'Tropical Flowers',
  'Orchid Specialist',
  'Rose Specialist',
  'Lily Specialist',
  'Flower Delivery Service',
  'Same Day Delivery',
  'International Delivery',
  
  // WEDDING DECORATION
  'Wedding Decorator',
  'Wedding Stage Decorator',
  'Wedding Hall Decorator',
  'Wedding Car Decorator',
  'Bridal Bouquet Designer',
  'Wedding Centerpieces',
  'Wedding Arch Decorator',
  'Wedding Backdrop Designer',
  'Wedding Aisle Decorator',
  'Reception Decorator',
  'Poruwa Decorator',
  'Traditional Wedding Decorator',
  'Modern Wedding Decorator',
  'Destination Wedding Decorator',
  'Beach Wedding Decorator',
  'Garden Wedding Decorator',
  'Hotel Wedding Decorator',
  
  // EVENT DECORATION
  'Event Decorator',
  'Party Decorator',
  'Birthday Party Decorator',
  'Kids Party Decorator',
  'Corporate Event Decorator',
  'Conference Decorator',
  'Exhibition Decorator',
  'Trade Show Decorator',
  'Product Launch Decorator',
  'Grand Opening Decorator',
  'Anniversary Decorator',
  'Engagement Party Decorator',
  'Baby Shower Decorator',
  'Bridal Shower Decorator',
  'Graduation Party Decorator',
  'Retirement Party Decorator',
  'Homecoming Decorator',
  
  // CULTURAL & RELIGIOUS
  'Temple Decorator',
  'Church Decorator',
  'Mosque Decorator',
  'Religious Event Decorator',
  'Festival Decorator',
  'Perahera Decorator',
  'Vesak Decorator',
  'Christmas Decorator',
  'New Year Decorator',
  'Diwali Decorator',
  'Eid Decorator',
  'Cultural Event Decorator',
  'Traditional Ceremony Decorator',
  
  // SPECIALTY DECORATION
  'Balloon Decorator',
  'Balloon Artist',
  'Balloon Arch Designer',
  'Balloon Bouquet Designer',
  'Stage Decorator',
  'Backdrop Designer',
  'Ceiling Decorator',
  'Wall Decorator',
  'Table Decorator',
  'Centerpiece Designer',
  'Lighting Decorator',
  'LED Decoration',
  'Fairy Light Decorator',
  'Draping Specialist',
  'Fabric Decorator',
  'Floral Wall Designer',
  'Photo Booth Decorator',
  'Entrance Decorator',
  'Outdoor Decorator',
  'Indoor Decorator',
  
  // THEME DECORATION
  'Theme Party Decorator',
  'Vintage Theme Decorator',
  'Rustic Theme Decorator',
  'Modern Theme Decorator',
  'Elegant Theme Decorator',
  'Bohemian Theme Decorator',
  'Garden Theme Decorator',
  'Beach Theme Decorator',
  'Tropical Theme Decorator',
  'Fairy Tale Theme Decorator',
  'Princess Theme Decorator',
  'Superhero Theme Decorator',
  'Cartoon Theme Decorator',
  'Movie Theme Decorator',
  
  // CORPORATE & BUSINESS
  'Corporate Decorator',
  'Office Decorator',
  'Business Event Decorator',
  'Conference Room Decorator',
  'Seminar Decorator',
  'Workshop Decorator',
  'Team Building Event Decorator',
  'Award Ceremony Decorator',
  'Gala Dinner Decorator',
  'Cocktail Party Decorator',
  
  // SEASONAL & HOLIDAY
  'Seasonal Decorator',
  'Holiday Decorator',
  'Christmas Decorator',
  'New Year Decorator',
  'Valentine Decorator',
  'Easter Decorator',
  'Halloween Decorator',
  'Thanksgiving Decorator',
  
  // SPECIALTY SERVICES
  'Luxury Decorator',
  'Budget Decorator',
  'DIY Decoration Consultant',
  'Decoration Rental Service',
  'Decoration Setup Service',
  'Full Service Decorator',
  'Decoration Consultant',
  'Custom Decoration Designer',
  'Eco-Friendly Decorator',
  'Sustainable Decoration',
  'Minimalist Decorator',
  'Maximalist Decorator',
  'Contemporary Decorator',
  'Classic Decorator'
];

