// Professional Driver Categories
export const DRIVER_CATEGORIES = [
  'School Bus Driver',
  'Child Transport',
  'Safety Certified',
  'Long Distance Driver',
  'City Transport',
  'Airport Transfer',
  'Wedding Transport',
  'Corporate Driver',
  'Tour Driver',
  'Luxury Vehicle Driver',
  'Van Driver',
  'Bus Driver',
  'Truck Driver',
  'Emergency Transport',
  'Medical Transport',
  'Elderly Care Transport',
  'Pet Transport',
  'Goods Transport',
  'Refrigerated Transport',
  'Heavy Vehicle Driver',
  'Light Vehicle Driver',
  'Motorcycle Rider',
  'Three Wheeler Driver',
  'Defensive Driving Certified',
  'First Aid Certified',
  'Night Shift Available',
  'Weekend Available',
  'Holiday Available',
  'English Speaking',
  'Multi-lingual',
  'GPS Navigation Expert',
  'Eco-Friendly Driving',
  'Fuel Efficient Driving',
  'VIP Transport',
  'Event Transport',
  'Festival Transport',
  'Religious Event Transport',
  'Sports Event Transport',
  'Concert Transport',
  'Hotel Transport'
];

