// Event & Update Categories for Events Management
export const EVENT_CATEGORIES = [
  // MUSIC & ENTERTAINMENT
  'Music Concert',
  'Live Band Performance',
  'DJ Night',
  'Music Festival',
  'Jazz Night',
  'Rock Concert',
  'Classical Music',
  'Traditional Music',
  'Karaoke Night',
  'Open Mic Night',
  
  // CULTURAL & TRADITIONAL
  'Cultural Festival',
  'Traditional Dance',
  'Cultural Show',
  'Heritage Event',
  'Religious Festival',
  'Temple Festival',
  'Perahera',
  'Cultural Exhibition',
  'Folk Performance',
  'Traditional Ceremony',
  
  // ARTS & CREATIVITY
  'Art Exhibition',
  'Art Gallery Opening',
  'Photography Exhibition',
  'Craft Fair',
  'Handicraft Exhibition',
  'Painting Workshop',
  'Sculpture Exhibition',
  'Street Art Festival',
  'Design Exhibition',
  'Creative Workshop',
  
  // FOOD & BEVERAGE
  'Food Festival',
  'Wine Tasting',
  'Beer Festival',
  'Street Food Fair',
  'Cooking Workshop',
  'Food Truck Festival',
  'Culinary Event',
  'Restaurant Opening',
  'Food & Wine Pairing',
  'Farmers Market',
  
  // SPORTS & FITNESS
  'Sports Event',
  'Marathon',
  'Cycling Event',
  'Yoga Session',
  'Fitness Workshop',
  'Sports Tournament',
  'Beach Sports',
  'Adventure Race',
  'Triathlon',
  'Fun Run',
  
  // EDUCATION & LEARNING
  'Workshop',
  'Seminar',
  'Conference',
  'Training Session',
  'Educational Talk',
  'Book Launch',
  'Book Fair',
  'Career Fair',
  'Tech Talk',
  'Masterclass',
  
  // BUSINESS & NETWORKING
  'Business Conference',
  'Networking Event',
  'Trade Show',
  'Expo',
  'Product Launch',
  'Startup Event',
  'Business Seminar',
  'Industry Meetup',
  'Corporate Event',
  'Professional Development',
  
  // COMMUNITY & SOCIAL
  'Community Gathering',
  'Charity Event',
  'Fundraiser',
  'Volunteer Event',
  'Social Meetup',
  'Beach Cleanup',
  'Tree Planting',
  'Community Service',
  'Awareness Campaign',
  'Social Cause Event',
  
  // CELEBRATIONS & PARTIES
  'New Year Celebration',
  'Birthday Party',
  'Anniversary Celebration',
  'Wedding Celebration',
  'Graduation Party',
  'Festival Celebration',
  'Holiday Party',
  'Theme Party',
  'Costume Party',
  'Dance Party',
  
  // NATURE & OUTDOOR
  'Nature Walk',
  'Hiking Event',
  'Camping Trip',
  'Beach Event',
  'Wildlife Safari',
  'Bird Watching',
  'Eco Tour',
  'Outdoor Adventure',
  'Sunset Viewing',
  'Stargazing Event',
  
  // FAMILY & KIDS
  'Family Event',
  'Kids Festival',
  'Children\'s Workshop',
  'Family Fun Day',
  'Kids Entertainment',
  'Educational Kids Event',
  'Family Picnic',
  'Kids Sports Day',
  'Children\'s Theater',
  'Family Movie Night',
  
  // TECHNOLOGY & INNOVATION
  'Tech Conference',
  'Hackathon',
  'Innovation Summit',
  'Tech Workshop',
  'Gaming Event',
  'Virtual Reality Experience',
  'Tech Expo',
  'Digital Marketing Event',
  'AI & ML Workshop',
  'Coding Bootcamp',
  
  // TOURISM & TRAVEL
  'Travel Fair',
  'Tourism Expo',
  'Destination Showcase',
  'Travel Workshop',
  'Adventure Tourism Event',
  'Eco Tourism Event',
  'Cultural Tourism',
  'Travel Photography',
  'Tourism Conference',
  'Travel Meetup',
  
  // GENERAL
  'Public Event',
  'Special Announcement',
  'Grand Opening',
  'Seasonal Event',
  'Limited Time Event',
  'Exclusive Event',
  'VIP Event',
  'Free Event',
  'Ticketed Event',
  'Other'
];

