// Vehicle Repairs & Mechanics Categories
export const VEHICLE_REPAIR_CATEGORIES = [
  // General Categories
  'General Mechanic',
  'Auto Electrician',
  'Body Shop Specialist',
  'Paint & Detailing Specialist',
  'Tire & Wheel Specialist',
  'Brake Specialist',
  'Engine Specialist',
  'Transmission Specialist',
  'Suspension & Steering Specialist',
  'Air Conditioning Specialist',
  'Exhaust System Specialist',
  'Diagnostic Specialist',
  
  // Vehicle Type Specialists
  'Car Mechanic',
  'Motorcycle Mechanic',
  'Three Wheeler Mechanic',
  'Van Mechanic',
  'Bus Mechanic',
  'Truck Mechanic',
  'Heavy Vehicle Mechanic',
  'Light Vehicle Mechanic',
  'Hybrid Vehicle Specialist',
  'Electric Vehicle Specialist',
  'Diesel Engine Specialist',
  'Petrol Engine Specialist',
  
  // Brand Specialists
  'Toyota Specialist',
  'Honda Specialist',
  'Nissan Specialist',
  'Suzuki Specialist',
  'Mitsubishi Specialist',
  'Mazda Specialist',
  'BMW Specialist',
  'Mercedes-Benz Specialist',
  'Audi Specialist',
  'Volkswagen Specialist',
  'Hyundai Specialist',
  'KIA Specialist',
  'Tata Specialist',
  'Mahindra Specialist',
  'Bajaj Specialist',
  'TVS Specialist',
  'Hero Specialist',
  'Yamaha Specialist',
  
  // Specialized Services
  'Dent Removal Specialist',
  'Windscreen Replacement',
  'Upholstery Specialist',
  'Car Wash & Detailing',
  'Ceramic Coating Specialist',
  'Tinting Specialist',
  'Sound System Installation',
  'GPS & Navigation Installation',
  'Dash Cam Installation',
  'Security System Installation',
  'Performance Tuning',
  'Engine Remapping',
  'Turbo Specialist',
  'Clutch Specialist',
  'Gearbox Specialist',
  'Differential Specialist',
  'Radiator Specialist',
  'Battery Specialist',
  'Alternator Specialist',
  'Starter Motor Specialist',
  
  // Certifications & Qualifications
  'Certified Technician',
  'ASE Certified',
  'Manufacturer Certified',
  'Hybrid Certified',
  'EV Certified',
  'Diesel Certified',
  'Safety Inspection Certified',
  'Emission Testing Certified',
  
  // Service Types
  'Mobile Mechanic',
  'Workshop Based',
  '24/7 Emergency Service',
  'Roadside Assistance',
  'Towing Service',
  'Pre-Purchase Inspection',
  'Regular Maintenance',
  'Oil Change Specialist',
  'Tune-Up Specialist',
  'Alignment Specialist',
  'Balancing Specialist',
  
  // Additional Services
  'Fleet Maintenance',
  'Commercial Vehicle Service',
  'Agricultural Vehicle Service',
  'Construction Vehicle Service',
  'Vintage Car Restoration',
  'Classic Car Specialist',
  'Racing Car Preparation',
  'Off-Road Vehicle Specialist',
  '4x4 Specialist',
  'Caravan & RV Specialist',
  
  // Quality & Experience
  'Premium Service',
  'Budget Friendly',
  'Quick Service',
  'Same Day Service',
  'Warranty Provided',
  'Insurance Approved',
  'Genuine Parts Only',
  'OEM Parts Specialist',
  'Aftermarket Parts',
  
  // Other
  'Multi-Brand Service',
  'All Vehicle Types',
  'Specialized Equipment',
  'Computer Diagnostics',
  'Advanced Technology',
  'Eco-Friendly Service',
  'Female Mechanic',
  'English Speaking',
  'Multi-lingual Service'
];

